Prevent multiple scripts from running concurrently due to online cron flukes. Fix time handling in archiving monitoring logs.

diff --git a/config/daily b/config/daily
--- a/config/daily
+++ b/config/daily
@@ -12,7 +12,9 @@ FILER=/dqmdata
 HERE=$(dirname $(dirname $0))
 [ X"$HERE" = X ] && { echo "$0: cannot figure out server location"; exit 1; }
 [ -d "$HERE/gui" ] || { echo "$0: server location '$HERE' is wrong"; exit 1; }
-[ -d "$FILER" ] || { echo "$0: filer location '$FILER' is wrong": exit 1; }
+[ -d "$FILER" ] || { echo "$0: filer location '$FILER' is wrong"; exit 1; }
+mkdir $HERE/.nodaily || { echo "$0: daily cannot run"; exit 1; }
+trap "rmdir $HERE/.nodaily" 0 1 2 15
 
 ######################################################################
 # File away server logs.
@@ -48,8 +50,7 @@ done
 
 ######################################################################
 # Compact monitoring logs.
-TIMELIMIT=$(date +%Y-%m-%d)
-for f in $FILER/status/*/$HOST/*/20[0-9][0-9][01][0-9]*.txt; do
+for f in $(find $FILER/status/*/$HOST/* -name '20[0-9][0-9][01][0-9]*.txt' -mmin +60 | sort); do
   set -e
   [ -f "$f" ] || continue
   month=$(echo "$f" | perl -pe 's|.*/||; s|^([0-9]{6}).*|$1|')
@@ -63,6 +64,6 @@ for f in $FILER/status/*/$HOST/*/20[0-9][0-9][01][0-9]*.txt; do
     continue ;;
   esac
 
-  zip -9Tmoqj -tt $TIMELIMIT $(dirname "$f")/$day.zip $f
+  zip -9Tmoqj $(dirname "$f")/$day.zip $f
   set +e
 done
