Update scripts for use with 'restart' and new documented procedures. Not for use yet.

diff --git a/config/startOnlineAgents b/config/startOnlineAgents
--- a/config/startOnlineAgents
+++ b/config/startOnlineAgents
@@ -1,12 +1,34 @@
 #!/bin/zsh
-DQM_V=5.1.4
-DQM_BASE=/home/dqm
-DQM_DATA=/dqmdata/dqm
-DQM_SW=$DQM_BASE/rpms
-. $DQM_SW/cmsset_default.sh
-. $DQM_SW/slc4_ia32_gcc345/cms/dqmgui/$DQM_V/etc/profile.d/env.sh
+
+# Set parameters. Use the latest installed server by default.
+DQMV=${1:-latest}
+ARCH=slc4_ia32_gcc345
+HOST=$(hostname)
 NOW=$(date +%Y%m%d%H%M%S)
 
+case $HOST in
+  srv-* ) DQM_DIR=/home/dqm DQM_SW=/home/dqm/rpms DQM_DATA=/dqmdata/dqm ;;
+  vocms* ) DQM_DIR=/data/dqm DQM_SW=/data/sw ;;
+esac
+
+if [ X"$DQMV" = Xlatest ]; then
+  DQMV=$(ls -tr $DQM_SW/$ARCH/cms/dqmgui | tail -1)
+fi
+
+# Source server environment. Move to $DQM_DIR so cwd is safe.
+cd $DQM_DIR
+. $DQM_SW/cmsset_default.sh
+. $DQM_SW/$ARCH/cms/dqmgui/$DQMV/etc/profile.d/env.sh
+
+# Verify invocation came from documented (copy-and-paste) instructions.
+CHECK=$(echo -n "$2" | tr -c '[A-Za-z]' '_' | tr '[:upper:]' '[:lower:]')
+if { ps -oargs= $PPID | grep -q -e /restart; } || \
+   [ X"$CHECK" = Xi_did_read_documentation ]; then :; else
+  echo "$0: cannot complete request, please check documentation."
+  exit 1
+fi
+
+# Start file handling agents.
 mkdir -p $DQM_DATA/repository/original \
          $DQM_DATA/repository/merged \
          $DQM_DATA/agents \
@@ -25,9 +47,9 @@ mkdir -p $DQM_DATA/repository/original \
   $DQM_BASE/ix \
 ) >& $DQM_BASE/agents/import-$NOW.log </dev/null &
 
-(visDQMMergeDaemon \
-  $DQM_DATA/agents/merge \
-  $DQM_DATA/repository/original \
-  $DQM_DATA/repository/merged \
-  $DQM_DATA/agents/t0xfer
-) >& $DQM_BASE/agents/merge-$NOW.log </dev/null &
+#(visDQMMergeDaemon \
+#  $DQM_DATA/agents/merge \
+#  $DQM_DATA/repository/original \
+#  $DQM_DATA/repository/merged \
+#  $DQM_DATA/agents/t0xfer
+#) >& $DQM_BASE/agents/merge-$NOW.log </dev/null &
